# Permalinks
permalink:           pretty

# Setup
title:               Charlie Yaris
tagline:             Data Scientist at Metis
url:                 http://cyaris.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Charlie Yaris
  url:               https://www.linkedin.com/in/charlieyaris/
  email:             charlieyaris@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cyaris

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
